---
version: 2
updates:
- package-ecosystem: "github-actions"
  directories:
  - "/"
  exclude-paths:
  - ".github/workflows/build.yml"
  - ".github/workflows/lint.yml"
  - ".github/workflows/push.yml"
  - ".github/actions"
  groups:
    minor-and-patch:
      applies-to: version-updates
      update-types:
      - "minor"
      - "patch"
  schedule:
    interval: "weekly"
    time: "09:00"
    timezone: "Europe/Oslo"
    day: "monday"
  open-pull-requests-limit: 2
- package-ecosystem: "github-actions"
  directories:
  - "/.github/workflows/build.yml"
  - "/.github/workflows/lint.yml"
  - "/.github/workflows/push.yml"
  - "/.github/actions/resolve-image"
  groups:
    minor-and-patch:
      applies-to: version-updates
      update-types:
      - "minor"
      - "patch"
  schedule:
    interval: "weekly"
    time: "09:00"
    timezone: "Europe/Oslo"
    day: "monday"
  open-pull-requests-limit: 2
  commit-message:
    prefix: "fix(deps):" # trigger new release when updating user-facing workflows
- package-ecosystem: "docker"
  directories:
  - /fixture
  groups:
    minor-and-patch:
      applies-to: version-updates
      update-types:
      - "minor"
      - "patch"
  schedule:
    interval: "weekly"
    time: "09:00"
    timezone: "Europe/Oslo"
    day: "monday"
  open-pull-requests-limit: 2
