FROM busybox:1.36
WORKDIR /usr/src/app
RUN --mount=type=secret,id=foo  --mount=type=secret,id=bar \
  FOO="$(cat /run/secrets/foo)" \
  BAR="$(cat /run/secrets/bar)" \
  echo "${FOO} ${BAR}" > buildargs.txt
CMD cat buildargs.txt