name: Entur/Meta/Doc
on:
  pull_request:

jobs:
  update-lint-doc:
    uses: entur/gha-meta/.github/workflows/auto-doc.yml@main
    with:
      workflow-file: .github/workflows/lint.yml
      readme-file: README-lint.md
