name: Entur/Docker/Build_and_Publish
on:
    workflow_call:
        inputs:
            dockerfile:
                description: 'Which dockerfile to run, default Dockerfile'
                type: string
            image_name:
                description: 'Name of the image to build'
                type: string
env:
    ENT_DOCKER_BUILD_DOCKERFILE: ${{ inputs.dockerfile || 'Dockerfile' }}
    ENT_DOCKER_BUILD_IMAGE_NAME: ${{ inputs.image_name || github.event.repository.name }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.1
            - name: Build Docker image
              run: docker build -t $ENT_DOCKER_BUILD_IMAGE_NAME -f $ENT_DOCKER_BUILD_DOCKERFILE 

        


