name: Entur/Docker/Build

on:
  workflow_call:
    inputs:
      dockerfile:
        description: "Dockerfile to use for build."
        type: string
        default: Dockerfile
      image_name:
        description: "Image name to use for the build. If not set repo name will be used."
        type: string
      artifact_name:
        description: "Name of GitHub artifact to add to build."
        type: string
      artifact_path:
        description: "Path to save artifact into. Default: build/libs"
        type: string
    outputs:
      image_name:
        value: ${{ jobs.build.outputs.image_name }}

env:
  ENT_DOCKER_ARTIFACT_PATH: ${{ inputs.artifact_path || 'build/libs' }}


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      image_name: ${{ env.ENT_DOCKER_BUILD_IMAGE_NAME }}.tar
    steps:
      - name: "Set environmental variables"
        if: ${{ inputs.image_name == '' }}
        run: |
          echo "ENT_DOCKER_BUILD_IMAGE_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
      - uses: actions/checkout@v4.1.1
      - id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - uses: actions/download-artifact@v4
        if: ${{ inputs.artifact_name != '' }}
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ env.ENT_DOCKER_ARTIFACT_PATH }}
      - uses: docker/setup-buildx-action@v3.1.0
      - id: build
        uses: docker/build-push-action@v5.2.0
        with:
          file: ${{ inputs.dockerfile || 'Dockerfile' }}
          push: false
          outputs: type=docker,dest=/tmp/${{ env.ENT_DOCKER_BUILD_IMAGE_NAME }}.tar
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - id: save-image
        uses: actions/upload-artifact@v4.3.1
        with:
          name: ${{ env.ENT_DOCKER_BUILD_IMAGE_NAME }}.tar
          path: /tmp/${{ env.ENT_DOCKER_BUILD_IMAGE_NAME }}.tar
          retention-days: 1
