name: Entur/Docker/Build

on:
  workflow_call:
    inputs:
      context:
        description: "Build context, default root of repository"
        type: string
        default: "."
      dockerfile:
        description: "Dockerfile to use for build"
        type: string
        default: "Dockerfile"
      image_name:
        description: "Image name to use for the build"
        type: string
        default: "repo_name"
      build_artifact_name:
        description: "Name of GitHub artifact to add to build"
        type: string
      build_artifact_path:
        description: "Path to the artifact"
        type: string
        default: "build/libs"
      timeout_minutes:
        description: "Timeout in minutes"
        type: number
        default: 40
    outputs:
      image_artifact:
        value: ${{ jobs.build.outputs.image_artifact }}
      image_tag:
        value: ${{ jobs.build.outputs.image_tag }}

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: ${{ inputs.timeout_minutes }}
    permissions:
      contents: read
    outputs:
      image_artifact: ${{ env.GHA_DOCKER_BUILD_IMAGE_NAME }}
      image_tag: ${{ env.GHA_DOCKER_BUILD_IMAGE_NAME }}:latest
    env:
      GHA_DOCKER_BUILD_CONTEXT: ${{ inputs.context }}
      GHA_DOCKER_BUILD_DOCKERFILE: ${{ inputs.dockerfile }}
      GHA_DOCKER_BUILD_ARTIFACT_PATH: ${{ inputs.build_artifact_path }}
      GHA_DOCKER_BUILD_ARTIFACT_NAME: ${{ inputs.build_artifact_name }}
      GHA_DOCKER_BUILD_IMAGE_NAME: ${{ inputs.image_name }}
    steps:
      - id: set-image-name
        shell: bash
        run: |
          if [[ "${GHA_DOCKER_BUILD_IMAGE_NAME}" = "repo_name" ]]; then
            echo "GHA_DOCKER_BUILD_IMAGE_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
          fi
      - uses: actions/checkout@v4.1.6
      - id: download-artifact
        uses: actions/download-artifact@v4
        if: env.GHA_DOCKER_BUILD_ARTIFACT_NAME != ''
        with:
          name: ${{ env.GHA_DOCKER_BUILD_ARTIFACT_NAME }}
          path: ${{ env.GHA_DOCKER_BUILD_ARTIFACT_PATH }}
      - id: debug-list-artifacts
        run: ls -R
      - id: setup-buildx
        uses: docker/setup-buildx-action@v3.3.0
      - id: debug-print-buildx-path
        run: echo ${{ steps.setup-buildx.outputs.name }}
      - id: build
        uses: docker/build-push-action@v5.3.0
        with:
          file: ${{ env.GHA_DOCKER_BUILD_DOCKERFILE }}
          push: false
          outputs: "type=docker,dest=/tmp/${{ env.GHA_DOCKER_BUILD_IMAGE_NAME }}.tar"
          cache-to: type=gha,mode=max
          tags: ${{ env.GHA_DOCKER_BUILD_IMAGE_NAME }}:latest
          provenance: false
          context: "{{defaultContext}}:${{ env.GHA_DOCKER_BUILD_CONTEXT }}"
      - id: debug-list-tmp-dir-post
        run: ls -R /tmp
      - id: save-image
        uses: actions/upload-artifact@v4.3.3
        with:
          name: ${{ env.GHA_DOCKER_BUILD_IMAGE_NAME }}
          path: /tmp/${{ env.GHA_DOCKER_BUILD_IMAGE_NAME }}.tar
          retention-days: 1
