name: Entur/Docker/CI

on:
  pull_request:

jobs:
  test-docker-lint-ok:
    name: Lint OK
    uses: ./.github/workflows/lint.yml
    with:
      dockerfile: fixture/Dockerfile.good
  test-docker-lint-ignore-ok:
    name: Lint Ignore OK
    uses: ./.github/workflows/lint.yml
    with:
      dockerfile: fixture/Dockerfile.bad
      ignore: DL3000
