name: Entur/Docker/CI

on:
  pull_request:

jobs:
  update-lint-doc:
    uses: entur/gha-meta/.github/workflows/auto-doc.yml@main
    with:
      workflow_file: .github/workflows/lint.yml
      readme_file: README-lint.md

  test-docker-lint-ok:
    name: Lint OK
    uses: ./.github/workflows/lint.yml
    with:
      dockerfile: fixture/Dockerfile.good

  test-docker-lint-ignore-ok:
    name: Lint Ignore OK
    uses: ./.github/workflows/lint.yml
    with:
      dockerfile: fixture/Dockerfile.bad
      ignore: DL3000

  test-docker-lint-fail-ok:
    name: Verify Lint Fail OK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: hadolint/hadolint-action@v3.1.0
        name: hadolint
        with:
          dockerfile: fixture/Dockerfile.bad
      - uses: nick-fields/assert-action@v1
        with:
          expected: failure
          actual: ${{ steps.hadolint.outcome }}
