name: Entur/Docker/CI

on:
  pull_request:

jobs:
  verify-pr:
    name: Verify PR
    if: ${{ github.event_name == 'pull_request' }}
    uses: entur/gha-meta/.github/workflows/verify-pr.yml@v1

  test-lint-ok:
    uses: ./.github/workflows/lint.yml
    with:
      dockerfile: fixture/Dockerfile.good
      timeout_minutes: 1

  test-lint-ignore-ok:
    uses: ./.github/workflows/lint.yml
    with:
      dockerfile: fixture/Dockerfile.bad
      ignore: DL3000

  assert-lint-fail-ok:
    runs-on: ubuntu-24.04
    env:
      HADOLINT_RESULTS: ""
    steps:
      - uses: actions/checkout@v5
      - uses: hadolint/hadolint-action@v3.3.0
        id: hadolint
        continue-on-error: true
        with:
          no-fail: true
          dockerfile: fixture/Dockerfile.bad
      - uses: nick-fields/assert-action@v2
        with:
          expected: "fixture/Dockerfile.bad:4 DL3000 error: Use absolute WORKDIR"
          actual: ${{ env.HADOLINT_RESULTS }}

  test-build-ok-with-secret:
    uses: ./.github/workflows/build.yml
    with:
      dockerfile: fixture/Dockerfile.secret
      image_name: ci-test-secret
    secrets:
      BUILD_SECRETS: |
        "MY_SECRET=${{ secrets.MY_SECRET }}"

  test-build-ok-with-git-ref:
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/build.yml
    with:
      dockerfile: fixture/Dockerfile.gitref
      image_name: ci-test-gitref
      git_ref: ${{ github.ref }} 

  test-build-prepare-artifact:
    needs: test-lint-ok
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/upload-artifact@v4
        with:
          name: build_artifact
          path: fixture/artifact.txt
          retention-days: 1
          overwrite: true

  test-build-ok-with-artifact:
    uses: ./.github/workflows/build.yml
    needs: test-build-prepare-artifact
    with:
      context: .
      dockerfile: fixture/Dockerfile.artifact
      build_artifact_name: build_artifact
      build_artifact_path: data

  test-build-prepare-additional-artifacts:
    needs: test-lint-ok
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/upload-artifact@v4
        with:
          name: build_artifact_additional
          path: |
            fixture/additional_artifact.txt
            fixture/test/additional_artifact_2.txt
          retention-days: 1
          overwrite: true

  test-build-ok-with-additional-artifacts:
    uses: ./.github/workflows/build.yml
    needs: test-build-prepare-additional-artifacts
    with:
      context: .
      dockerfile: fixture/Dockerfile.artifacts
      image_name: gha-docker-additional_artifacts
      build_artifact_name: build_artifact_additional
      build_artifact_path: data
      additional_artifacts_name: extras
      additional_artifacts_paths: |
        /usr/src/app/main/resources/additional_artifact_2.txt
  
  assert-additional-artifacts-outputs-ok:
    needs: test-build-ok-with-additional-artifacts
    runs-on: ubuntu-24.04
    steps:
      - uses: nick-fields/assert-action@v2
        with:
          expected: "extras"
          actual: ${{ needs.test-build-ok-with-additional-artifacts.outputs.additional_artifacts }}

  test-push-gcr-ok:
    needs: test-build-ok-with-artifact
    uses: ./.github/workflows/push.yml
    with:
      context: .
      dockerfile: fixture/Dockerfile.artifact

  test-push-gcr-ok-with-tag:
    needs: test-push-gcr-ok
    uses: ./.github/workflows/push.yml
    with:
      context: .
      dockerfile: fixture/Dockerfile.artifact
      image_tag: ci-test-tag
      git_tag: false
       
  assert-tag-gcr-outputs-ok:
    needs: test-push-gcr-ok-with-tag
    runs-on: ubuntu-24.04
    steps:
      - uses: nick-fields/assert-action@v2
        with:
          expected: "ci-test-tag"
          actual: ${{ needs.test-push-gcr-ok-with-tag.outputs.image_tag }}

  test-push-gcr-ok-with-multiple-tags:
    needs: test-push-gcr-ok
    uses: ./.github/workflows/push.yml
    with:
      context: .
      dockerfile: fixture/Dockerfile.artifact
      image_tag: ci-test-tag
      extra_image_tags: ci-test-tag-2,ci-test-tag-3
      git_tag: false

  assert-multiple-tags-gcr-outputs-ok:
    needs: test-push-gcr-ok-with-multiple-tags
    runs-on: ubuntu-24.04
    steps:
      - uses: nick-fields/assert-action@v2
        with:
          expected: "ci-test-tag,ci-test-tag-2,ci-test-tag-3"
          actual: ${{ needs.test-push-gcr-ok-with-multiple-tags.outputs.all_image_tags }}

  test-push-gcr-ok-with-git-ref:
    needs: test-push-gcr-ok
    uses: ./.github/workflows/push.yml
    with:
      context: .
      dockerfile: fixture/Dockerfile.artifact
      git_ref: main
      git_tag: false
      
  assert-tag-gcr-outputs-ok-with-git-ref:
    needs: test-push-gcr-ok-with-git-ref
    runs-on: ubuntu-24.04
    steps: 
      - uses: nick-fields/assert-action@v2
        with:
          expected: main
          actual: ${{ needs.test-push-gcr-ok-with-git-ref.outputs.image_tag }}
          comparison: endsWith

  test-build-ok-with-custom-image-name:
    uses: ./.github/workflows/build.yml
    with:
      dockerfile: fixture/Dockerfile.good
      image_name: custom_image_name

  assert-build-ok-with-custom-image-name-outputs:
    runs-on: ubuntu-24.04
    needs: test-build-ok-with-custom-image-name
    steps: 
      - uses: nick-fields/assert-action@v2
        with:
          expected: "custom_image_name"
          actual: ${{ needs.test-build-ok-with-custom-image-name.outputs.image_artifact }}

  test-push-acr-ok-with-tag:
    needs: test-build-ok-with-artifact
    uses: ./.github/workflows/push.yml
    with:
      cloud_provider: az
      context: .
      dockerfile: fixture/Dockerfile.artifact
      image_tag: ci-test-az-tag
      git_tag: false

  assert-tag-acr-outputs-ok:
    runs-on: ubuntu-24.04
    needs: test-push-acr-ok-with-tag
    steps:
      - uses: nick-fields/assert-action@v2
        with:
          expected: "ci-test-az-tag"
          actual: ${{ needs.test-push-acr-ok-with-tag.outputs.image_tag }}

  test-push-acr-ok-with-multiple-tags:
    needs: test-build-ok-with-artifact
    uses: ./.github/workflows/push.yml
    with:
      cloud_provider: az
      context: .
      dockerfile: fixture/Dockerfile.artifact
      image_tag: ci-test-az-tag
      extra_image_tags: ci-test-az-tag-2,ci-test-az-tag-3
      git_tag: false

  assert-multiple-tags-acr-outputs-ok:
    runs-on: ubuntu-24.04
    needs: test-push-acr-ok-with-multiple-tags
    steps:
      - uses: nick-fields/assert-action@v2
        with:
          expected: "ci-test-az-tag,ci-test-az-tag-2,ci-test-az-tag-3"
          actual: ${{ needs.test-push-acr-ok-with-multiple-tags.outputs.all_image_tags }}

  update-lint-doc:
    needs:
      [
        assert-tag-gcr-outputs-ok,
        assert-multiple-tags-gcr-outputs-ok,
        assert-tag-acr-outputs-ok,
        assert-multiple-tags-acr-outputs-ok,
        assert-build-ok-with-custom-image-name-outputs,
        assert-additional-artifacts-outputs-ok,
      ]
    uses: entur/gha-meta/.github/workflows/auto-doc.yml@v1
    with:
      workflow_file: .github/workflows/lint.yml
      readme_file: README-lint.md

  update-build-doc:
    needs:
      [
        assert-tag-gcr-outputs-ok,
        assert-multiple-tags-gcr-outputs-ok,
        assert-tag-acr-outputs-ok,
        assert-multiple-tags-acr-outputs-ok,
        assert-build-ok-with-custom-image-name-outputs,
        update-lint-doc,
      ]
    uses: entur/gha-meta/.github/workflows/auto-doc.yml@v1
    with:
      workflow_file: .github/workflows/build.yml
      readme_file: README-build.md

  update-push-doc:
    needs:
      [
        assert-tag-gcr-outputs-ok,
        assert-multiple-tags-gcr-outputs-ok,
        assert-tag-acr-outputs-ok,
        assert-multiple-tags-acr-outputs-ok,
        assert-build-ok-with-custom-image-name-outputs,
        update-build-doc,
      ]
    uses: entur/gha-meta/.github/workflows/auto-doc.yml@v1
    with:
      workflow_file: .github/workflows/push.yml
      readme_file: README-push.md
