name: Entur/Docker/CI

on:
  pull_request:

jobs:
  update-lint-doc:
    uses: entur/gha-meta/.github/workflows/auto-doc.yml@main
    with:
      workflow_file: .github/workflows/lint.yml
      readme_file: README-lint.md
  test-docker-lint-ok:
    name: Lint OK
    uses: ./.github/workflows/lint.yml
    with:
      dockerfile: fixture/Dockerfile.good
  test-docker-lint-ignore-ok:
    name: Lint Ignore OK
    uses: ./.github/workflows/lint.yml
    with:
      dockerfile: fixture/Dockerfile.bad
      ignore: DL3000
  test-docker-lint-fail-ok:
    name: Lint Ignore Fail OK
    runs-on: ubuntu-latest
    steps:
      - name: Run failed test
        id: fail-test
        uses: ./.github/workflows/lint.yml
        with:
          dockerfile: fixture/Dockerfile.bad
      - name: Run assertion
        uses: nick-fields/assert-action@v1
        with:
            expected: failure
            actual: ${{ steps.fail-test.outcome }}
