name: Entur/Docker/CI

on:
  pull_request:

jobs:
  test-lint-ok:
    uses: ./.github/workflows/lint.yml
    with:
      dockerfile: fixture/Dockerfile.good
      timeout_minutes: 1

  test-lint-ignore-ok:
    uses: ./.github/workflows/lint.yml
    with:
      dockerfile: fixture/Dockerfile.bad
      ignore: DL3000

  assert-lint-fail-ok:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: hadolint/hadolint-action@v3.1.0
        id: hadolint
        continue-on-error: true
        with:
          no-fail: true
          dockerfile: fixture/Dockerfile.bad
      - uses: nick-fields/assert-action@v2
        with:
          expected: "fixture/Dockerfile.bad:4 DL3000 error: Use absolute WORKDIR"
          actual: ${{ env.HADOLINT_RESULTS }}

  test-build-prepare-artifact:
    needs: test-lint-ok
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/upload-artifact@v4.3.3
        with:
          name: some_build_artifact
          path: fixture/artifact.txt
          retention-days: 1
          overwrite: true

  test-build-ok-with-artifact:
    uses: ./.github/workflows/build.yml
    needs: test-build-prepare-artifact
    with:
      context: .
      dockerfile: fixture/Dockerfile.artifact
      build_artifact_name: some_build_artifact
      build_artifact_path: data

  test-push-gcr-ok:
    needs: test-build-ok-with-artifact
    uses: ./.github/workflows/push.yml
    with:
      context: .
      dockerfile: fixture/Dockerfile.artifact

  test-push-gcr-ok-with-tag:
    needs: test-push-gcr-ok
    uses: ./.github/workflows/push.yml
    with:
      context: .
      dockerfile: fixture/Dockerfile.artifact
      image_tag: ci-test-tag
      git_tag: false

  assert-tag-gcr-outputs-ok:
    needs: test-push-gcr-ok-with-tag
    runs-on: ubuntu-24.04
    steps:
      - uses: nick-fields/assert-action@v2
        with:
          expected: "ci-test-tag"
          actual: ${{ needs.test-push-gcr-ok-with-tag.outputs.image_tag }}

  test-build-ok-with-custom-image-name:
    uses: ./.github/workflows/build.yml
    with:
      dockerfile: fixture/Dockerfile.good
      image_name: custom_image_name

  assert-build-ok-with-custom-image-name-outputs:
    runs-on: ubuntu-24.04
    needs: test-build-ok-with-custom-image-name
    steps:
      - uses: nick-fields/assert-action@v2
        with:
          expected: "custom_image_name:latest"
          actual: ${{ needs.test-build-ok-with-custom-image-name.outputs.image_tag }}
      - uses: nick-fields/assert-action@v2
        with:
          expected: "custom_image_name"
          actual: ${{ needs.test-build-ok-with-custom-image-name.outputs.image_artifact }}

  test-push-acr-ok-with-tag:
    needs: test-build-ok-with-artifact
    uses: ./.github/workflows/push.yml
    with:
      cloud_provider: az
      context: .
      dockerfile: fixture/Dockerfile.artifact
      image_tag: ci-test-az-tag
      git_tag: false

  assert-tag-acr-outputs-ok:
    runs-on: ubuntu-24.04
    needs: test-push-acr-ok-with-tag
    steps:
      - uses: nick-fields/assert-action@v2
        with:
          expected: "ci-test-az-tag"
          actual: ${{ needs.test-push-acr-ok-with-tag.outputs.image_tag }}

  update-lint-doc:
    needs:
      [
        test-push-acr-ok-with-tag,
        assert-build-ok-with-custom-image-name-outputs,
      ]
    uses: entur/gha-meta/.github/workflows/auto-doc.yml@v1
    with:
      workflow_file: .github/workflows/lint.yml
      readme_file: README-lint.md

  update-build-doc:
    needs:
      [
        test-push-acr-ok-with-tag,
        assert-build-ok-with-custom-image-name-outputs,
        update-lint-doc,
      ]
    uses: entur/gha-meta/.github/workflows/auto-doc.yml@v1
    with:
      workflow_file: .github/workflows/build.yml
      readme_file: README-build.md

  update-push-doc:
    needs:
      [
        test-push-acr-ok-with-tag,
        assert-build-ok-with-custom-image-name-outputs,
        update-build-doc,
      ]
    uses: entur/gha-meta/.github/workflows/auto-doc.yml@v1
    with:
      workflow_file: .github/workflows/push.yml
      readme_file: README-push.md
