name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-docker-lint-ok:
    name: Lint OK
    uses: ./.github/workflows/lint.yaml
    with:
      dockerfile: fixture/Dockerfile.good
  test-docker-lint-ignore-ok:
    name: Lint Ignore OK
    uses: ./.github/workflows/lint.yaml
    with:
      dockerfile: fixture/Dockerfile.bad
      ignores: DL3000
